---
driver:
  name: vagrant

provisioner:
  name: chef_zero

driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.1
  - name: debian-6.0.10
    run_list:
    - recipe[apt]
  - name: debian-7.8
    run_list:
    - recipe[apt]
  - name: fedora-20
  - name: fedora-21
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[stompserver::default]
